apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./argo-user-role.yaml
  - ./default-sa-role.yaml
  - ./default-sa-rolebinding.yaml
  - github.com/argoproj/argo/manifests/namespace-install?ref=v2.8.1
