apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aiops-prod-argo

commonLabels:
  app.kubernetes.io/name: argo
  app.kubernetes.io/component: workflow-engine
  app.kubernetes.io/part-of: aiops-analytics
  app.kubernetes.io/managed-by: aicoe-aiops-devops-argocd

resources:
  - ../../base
  - ./membership.yaml
