apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project-admins-aiops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: Group
    name: aicoe-aiops-devops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: Group
    name: data-hub-admins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project-argo-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-user
subjects:
  - kind: Group
    name: data-hub-admins
  - kind: Group
    name: aicoe-aiops-devops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: argocd-manager
    namespace: aicoe-argocd
