apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    jupyterhub: singleuser-profiles

configMapGenerator:
- name: jupyterhub-custom-profiles
  files:
    - jupyterhub-singleuser-profiles.yaml
