---
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: project-admins
roleRef:
  name: admin
subjects:
  - kind: 'Group'
    name: data-hub-openshift-admins
groupNames:
  - data-hub-openshift-admins
---
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: project-viewers
roleRef:
  name: view
subjects:
  - kind: 'SystemGroup'
    name: system:authenticated
groupNames:
  - system:authenticated
userNames: null
