---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: cuda

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: 10.0-base-ubi7
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'cuda:10.0-base-ubi7'
  resources:
    limits:
      cpu: '4'
      memory: 4Gi
    requests:
      cpu: '4'
      memory: 4Gi
  source:
    contextDir: 10.0/base
    git:
      ref: ubi7
      uri: 'https://github.com/sub-mod/cuda.git'
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
      env:
        - name: S2I_IMAGE
          value: 'registry.access.redhat.com/ubi7/s2i-base:latest'
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/ubi7/s2i-base:latest'
      noCache: true
    type: Docker
  triggers:
    - type: ConfigChange

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: 10.0-runtime-ubi7
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'cuda:10.0-runtime-ubi7'
  resources:
    limits:
      cpu: '4'
      memory: 4Gi
    requests:
      cpu: '4'
      memory: 4Gi
  source:
    contextDir: 10.0/runtime
    git:
      ref: ubi7
      uri: 'https://github.com/sub-mod/cuda.git'
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'cuda:10.0-base-ubi7'
      noCache: true
    type: Docker
  triggers:
    - type: ConfigChange
    - type: ImageChange

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: 10.0-devel-ubi7
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'cuda:10.0-devel-ubi7'
  resources:
    limits:
      cpu: '4'
      memory: 4Gi
    requests:
      cpu: '4'
      memory: 4Gi
  source:
    contextDir: 10.0/devel
    git:
      ref: ubi7
      uri: 'https://github.com/sub-mod/cuda.git'
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'cuda:10.0-runtime-ubi7'
      noCache: true
    type: Docker
  triggers:
    - type: ConfigChange
    - type: ImageChange

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: 10.0-cudnn7-devel-ubi7
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'cuda:10.0-cudnn7-devel-ubi7'
  resources:
    limits:
      cpu: '4'
      memory: 4Gi
    requests:
      cpu: '4'
      memory: 4Gi
  source:
    contextDir: 10.0/devel/cudnn7
    git:
      ref: ubi7
      uri: 'https://github.com/sub-mod/cuda.git'
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'cuda:10.0-devel-ubi7'
      noCache: true
    type: Docker
  triggers:
    - type: ConfigChange
    - type: ImageChange

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: python-36-ubi7

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: python-36-ubi7
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'python-36-ubi7:10.0-cudnn7-devel-ubi7'
  resources:
    limits:
      cpu: '4'
      memory: 4Gi
    requests:
      cpu: '4'
      memory: 4Gi
  source:
    contextDir: '3.6'
    git:
      ref: master
      uri: 'https://github.com/sclorg/s2i-python-container.git'
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile.rhel7
      from:
        kind: ImageStreamTag
        name: 'cuda:10.0-cudnn7-devel-ubi7'
      noCache: true
    type: Docker
  triggers:
    - type: ConfigChange
    - type: ImageChange

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-minimal-notebook

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: s2i-minimal-notebook
spec:
  output:
    to:
      kind: ImageStreamTag
      name: s2i-minimal-notebook:3.6
  resources:
    limits:
      memory: 1Gi
  source:
    contextDir: minimal-notebook
    git:
      uri: https://github.com/vpavlin/jupyter-notebooks
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: quay.io/vpavlin/python-36-ubi7:ubi
    type: Source
  triggers:
    - type: ConfigChange

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-minimal-notebook-gpu

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: s2i-minimal-notebook-gpu
spec:
  output:
    to:
      kind: ImageStreamTag
      name: s2i-minimal-notebook-gpu:3.6
  resources:
    limits:
      memory: 1Gi
  source:
    contextDir: minimal-notebook
    git:
      uri: https://github.com/vpavlin/jupyter-notebooks
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python-36-ubi7:10.0-cudnn7-devel-ubi7
    type: Source
  triggers:
    - type: ConfigChange
    - type: ImageChange

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-scipy-notebook

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-spark-minimal-notebook

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-spark-minimal-notebook-with-libsndfile

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: s2i-spark-minimal-notebook-with-libsndfile
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 's2i-spark-minimal-notebook-with-libsndfile:3.6'
  resources:
    limits:
      memory: 1Gi
  source:
    contextDir: minimal-notebook
    git:
      uri: 'https://github.com/aakankshaduggal/jupyter-notebooks'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'quay.io/aduggal/python36-spark-ubi7-with-libsndfile:latest'
    type: Source
  triggers:
    - type: ConfigChange

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: s2i-scipy-notebook
spec:
  output:
    to:
      kind: ImageStreamTag
      name: s2i-scipy-notebook:3.6
  resources:
    limits:
      memory: 1Gi
  source:
    contextDir: scipy-notebook
    git:
      uri: https://github.com/vpavlin/jupyter-notebooks
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-minimal-notebook:3.6
    type: Source
  triggers:
    - type: ConfigChange
    - type: ImageChange

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-spark-scipy-notebook-with-libsndfile

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: s2i-spark-scipy-notebook-with-libsndfile
  name: s2i-spark-scipy-notebook-with-libsndfile
spec:
  output:
    to:
      kind: ImageStreamTag
      name: s2i-spark-scipy-notebook-with-libsndfile:3.6
  resources:
    limits:
      memory: 1Gi
  source:
    contextDir: scipy-notebook
    git:
      uri: https://github.com/aakankshaduggal/jupyter-notebooks
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-spark-minimal-notebook-with-libsndfile:3.6
    type: Source
  triggers:
    - type: ConfigChange
    - type: ImageChange

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-spark24-minimal-notebook

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: s2i-spark24-minimal-notebook
  name: s2i-spark24-minimal-notebook
spec:
  output:
    to:
      kind: ImageStreamTag
      name: s2i-spark24-minimal-notebook:3.6
  resources:
    limits:
      memory: 1Gi
  source:
    contextDir: minimal-notebook
    git:
      uri: https://github.com/vpavlin/jupyter-notebooks
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: quay.io/vpavlin/python36-spark-ubi7:feature_spark-2.4
    type: Source
  triggers:
    - type: ConfigChange

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-spark24-scipy-notebook

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: s2i-spark24-scipy-notebook
spec:
  output:
    to:
      kind: ImageStreamTag
      name: s2i-spark24-scipy-notebook:3.6
  resources:
    limits:
      memory: 1Gi
  source:
    contextDir: scipy-notebook
    git:
      uri: https://github.com/vpavlin/jupyter-notebooks
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-spark24-minimal-notebook:3.6
    type: Source
  triggers:
    - type: ConfigChange
    - type: ImageChange

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-tensorflow-notebook

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: s2i-tensorflow-notebook
spec:
  output:
    to:
      kind: ImageStreamTag
      name: s2i-tensorflow-notebook:3.6
  resources:
    limits:
      memory: 512Mi
  source:
    contextDir: tensorflow-notebook
    git:
      uri: https://github.com/vpavlin/jupyter-notebooks
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-minimal-notebook:3.6
    type: Source
  triggers:
    - type: ConfigChange
    - type: ImageChange

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-tensorflow-gpu-base

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: s2i-tensorflow-gpu-base
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 's2i-tensorflow-gpu-base:3.6'
  resources:
    limits:
      memory: 512Mi
  source:
    contextDir: tensorflow-notebook
    git:
      ref: feature/add-tf-gpu
      uri: 'https://github.com/vpavlin/jupyter-notebooks'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 's2i-minimal-notebook-gpu:3.6'
    type: Source
  triggers:
    - type: ConfigChange
    - type: ImageChange

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-tensorflow-notebook-gpu

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: s2i-tensorflow-notebook-gpu
spec:
  output:
    to:
      kind: ImageStreamTag
      name: s2i-tensorflow-notebook-gpu:3.6
  resources:
    limits:
      memory: 512Mi
  source:
    contextDir: tensorflow-notebook-gpu
    git:
      ref: feature/add-tf-gpu
      uri: https://github.com/vpavlin/jupyter-notebooks
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-tensorflow-gpu-base:3.6
    type: Source
  triggers:
    - type: ConfigChange
    - type: ImageChange

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-thoth-notebook

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: s2i-thoth-notebook
spec:
  output:
    to:
      kind: ImageStreamTag
      name: s2i-thoth-notebook:3.6
  resources:
    limits:
      memory: 512Mi
  source:
    git:
      ref: master
      uri: https://github.com/thoth-station/jupyter-notebook
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-minimal-notebook:3.6
    type: Source
  triggers:
    - type: ConfigChange
    - type: ImageChange

# AIOps Data Sci Demo images

## OCP4 Anomaly Detection Image from https://gitlab.cee.redhat.com/AICoE/ocp4
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-ocp4-anomaly-detection-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: docker-registry.upshift.redhat.com/aicoe-notebooks/ocp4-anomaly-detection:latest
    importPolicy:
      scheduled: true
    name: "latest"

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  name: s2i-drift-analysis-notebook
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: docker-registry.upshift.redhat.com/aicoe-notebooks/drift-analysis-baselines:latest
    importPolicy:
      scheduled: true
    name: "latest"
    
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  name: s2i-categorical-encoding
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: docker-registry.upshift.redhat.com/aicoe-notebooks/categorical-encoding:latest
    importPolicy:
      scheduled: true
    name: "latest"
