apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: prometheus-route
  namespace: dh-psi-monitoring
spec:
  path: /
  to:
    kind: Service
    name: prometheus-operated
  port:
    targetPort: 9090
