apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-events-user
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - gateways
      - gateways/finalizers
      - sensors
      - sensors/finalizers
      - eventsources
      - eventsources/finalizers
      - eventbuses
      - eventbuses/finalizers
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
