apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./argo-events-user-role.yaml
  - ./argo-events-user-rolebinding.yaml
  - github.com/argoproj/argo-events/manifests/namespace-install?ref=v0.15.0
