apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./argo-events-user-role.yaml
  - github.com/argoproj/argo-events/manifests/namespace-install?ref=v0.16.0
  - https://raw.githubusercontent.com/argoproj/argo-events/v0.16.0/manifests/cluster-install/rbac/argo-events-aggregate-to-admin.yaml
  - https://raw.githubusercontent.com/argoproj/argo-events/v0.16.0/manifests/cluster-install/rbac/argo-events-aggregate-to-edit.yaml
  - https://raw.githubusercontent.com/argoproj/argo-events/v0.16.0/manifests/cluster-install/rbac/argo-events-aggregate-to-view.yaml
#
