apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dh-stage-argo

commonLabels:
  app.kubernetes.io/name: data-hub
  app.kubernetes.io/component: argo-events
  app.kubernetes.io/managed-by: aicoe-data-hub-argocd

resources:
  - ../../base
  - ./membership.yaml

patchesJson6902:
  - patch: |
      - op: replace
        path: /data/config
        value: |
          namespace: dh-stage-argo
    target:
      kind: ConfigMap
      name: gateway-controller-configmap
      version: v1
  - patch: |
      - op: replace
        path: /data/config
        value: |
          namespace: dh-stage-argo
    target:
      kind: ConfigMap
      name: sensor-controller-configmap
      version: v1
