apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project-argo-events-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-events-user
subjects:
  - kind: Group
    name: data-hub
