apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dh-prod-argo

resources:
  - ../../base
  - ./membership.yaml

patchesStrategicMerge:
  - argo-events-user-rolebinding.yaml
