apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: project-admins
roleRef:
  name: admin
subjects:
  - kind: Group
    name: data-hub-admins
---
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: project-viewers
roleRef:
  name: view
subjects:
  - kind: Group
    name: data-hub
