apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: project-admins
roleRef:
  name: admin
subjects:
  - kind: Group
    name: data-hub-admins
---
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: project-viewers
roleRef:
  name: view
subjects:
  - kind: Group
    name: data-hub
---
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: project-argo-events-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-events-user
subjects:
  - kind: Group
    name: data-hub-admins
  - kind: Group
    name: data-hub
