apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dh-stage-argo

commonLabels:
  app.kubernetes.io/name: data-hub
  app.kubernetes.io/component: argo
  app.kubernetes.io/managed-by: aicoe-data-hub-argocd

resources:
  - ../../base
  - ./membership.yaml
